--- #YAML:1.0
name:               Digest-MD6
version:            0.03
abstract:           ~
author:
    - Andy Armstrong <andy@hexten.net>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Digest::base:  1.00
    File::Spec:    0
    Test::More:    0
    XSLoader:      0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
